///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Images {
  Images._();

  static const String assetsCardBackground = 'assets/card_background.png';
  static const String assetsCourse = 'assets/course.png';
  static const String assetsGallery = 'assets/gallery.svg';
  static const String assetsMentorImage = 'assets/mentor-image.jpg';
}
